### ISSUE TITLE
Data source looping whill using data source next raw 

### ISSUE THREAD

**Issue by naniking** [rse/vmix-scripts#1]
Need help to loop the data sources for a animation loop using pages but unable to loop the data sources when using the select data source next raw

**Comment by rse** [comment]
Sorry, you have to be more precise: (1) what script of my collection are you talking about and (2) what problem do you have with the script?

**Comment by naniking** [comment]
thanks for the reply, is it possible to compile vmix scripts into dll files
to secure

**Comment by rse** [comment]
No, they are loaded as source files on vMix start. Whether they are internally compiled I don't know. But you cannot provide them as DLL files.
